jobs:
  build:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - setup_remote_docker

      # Whatever you want to do
      - run: sudo apt-get update
      - run: echo "this is a test!"
      - run:
          name: build & run image
          command: |
            docker build -t gitlab.nitsan-dg.com:5050/weather-generic/weather:${CIRCLE_BUILD_NUM} -f website/Dockerfile website
            docker run -d -p 5000:5000 -e WEATHER_KEY=$WEATHER_KEY --name target_container gitlab.nitsan-dg.com:5050/weather-generic/weather:${CIRCLE_BUILD_NUM}
      - run:
          name: test it!
          command: |
            docker build -t website_tests -f tests/Dockerfile tests
            docker run --name test_website --net=host website_tests
      - run:
          name: upload it!
          command: |
            docker login gitlab.nitsan-dg.com:5050 -u $docker_user -p $docker_pass
            docker push gitlab.nitsan-dg.com:5050/weather-generic/weather:${CIRCLE_BUILD_NUM}
      - run:
          name: update discord!!
          when: on_success
          command: |
            curl -X POST $discord_webhook -H "Content-Type: application/json" -d '{"content": "circleCI pipline weather build number ${CIRCLE_BUILD_NUM} SUCCEEDED"}'
      - run:
          name: update discord!!
          when: on_fail
          command: |
            curl -X POST $discord_webhook -H "Content-Type: application/json" -d '{"content": "circleCI pipline weather build number ${CIRCLE_BUILD_NUM} FAILED"}'


